version: "3.8"

services:
  backend:
    image: eclipse-temurin:21-jre-alpine
    container_name: portfolio-backend
    volumes:
      - ./app.jar:/app/app.jar
    working_dir: /app
    command: java -jar app.jar
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always